FROM    centos:centos6

RUN	yum install -y wget tar 

RUN	wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.tar.gz"
RUN	tar xvf jdk-8u45-linux-x64.tar.gz
ENV	JAVA_HOME $HOME/jdk1.8.0_45

# Bundle source
COPY	FinanceStreamSimulator .
